# Generated by Django 5.0.4 on 2024-09-20 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crianca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeDaCrianca", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("masculino", "masculino"), ("feminino", "feminino")],
                        default="masculino",
                        max_length=30,
                    ),
                ),
                ("nomeDaMae", models.CharField(max_length=150)),
                ("cpfDaMae", models.CharField(max_length=14)),
                ("dataNascimento", models.CharField(max_length=20)),
                (
                    "idadeCrianca",
                    models.CharField(
                        choices=[
                            ("primeira semana", "primeira semana"),
                            ("1 mês", "1 mês"),
                            ("2 meses", "2 meses"),
                            ("4 meses", "4 meses"),
                            ("6 meses", "6 meses"),
                            ("9 meses", "9 meses"),
                            ("12 meses", "12 meses"),
                            ("15 meses", "15 meses"),
                            ("18 meses", "18 meses"),
                            ("24 meses", "24 meses"),
                            ("30 meses", "30 meses"),
                            ("36 meses", "36 meses"),
                            ("42 meses", "42 meses"),
                        ],
                        max_length=30,
                    ),
                ),
                ("maternidade", models.CharField(max_length=150)),
                ("tipoDoParto", models.CharField(max_length=150)),
                ("idadeGestacional", models.CharField(max_length=150)),
                ("dataNascimentoMae", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logradouro", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=9)),
                ("numero", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=50)),
                ("municipio", models.CharField(max_length=20)),
                ("complemento", models.CharField(max_length=100)),
                ("nomeUSF", models.CharField(default="USF", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CrescimentoCrianca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idadeCrianca",
                    models.CharField(
                        choices=[
                            ("primeira semana", "primeira semana"),
                            ("1 mês", "1 mês"),
                            ("2 meses", "2 meses"),
                            ("4 meses", "4 meses"),
                            ("6 meses", "6 meses"),
                            ("9 meses", "9 meses"),
                            ("12 meses", "12 meses"),
                            ("15 meses", "15 meses"),
                            ("18 meses", "18 meses"),
                            ("24 meses", "24 meses"),
                            ("30 meses", "30 meses"),
                            ("36 meses", "36 meses"),
                            ("42 meses", "42 meses"),
                        ],
                        max_length=20,
                    ),
                ),
                ("altura", models.FloatField()),
                ("peso", models.FloatField()),
                ("perimetro", models.FloatField()),
                ("imc", models.FloatField(blank=True, null=True)),
                (
                    "idCrianca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.crianca",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeSaudeFamiliar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("criadoEmDiaMesAno", models.DateField(auto_now_add=True)),
                (
                    "endereco",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.endereco",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrupoUsf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=180)),
                (
                    "usf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos",
                        to="project.unidadesaudefamiliar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profissionais",
                        to="project.grupousf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CriancaProfissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criadoEmDiaMesAno", models.DateField(auto_now_add=True)),
                (
                    "idCrianca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profissionais",
                        to="project.crianca",
                    ),
                ),
                (
                    "idProfissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criancas",
                        to="project.user",
                    ),
                ),
            ],
        ),
    ]
